### ISSUE TITLE
Worldgen: generated contract interface excludes inherited contract(s)

### ISSUE THREAD

**Issue by 0xhank** [latticexyz/mud#976] opened 2023-05-25 11:09 UTC
I have a smart contract that inherits another smart contract:
```
contract ERC20TestSystem is ERC20System{

  constructor(string memory _name, string memory _symbol) ERC20System(_name, _symbol) {}

  function mint(address to, uint256 amount) public{
    _mint(to, amount);
  }

  function burn(address from, uint256 amount) public {
    _burn(from, amount);
  }
}
```

On system interface generation, I want the contract interface to inherit IERC20System so function registration occurs properly. Instead, the interface looks like: 

```
interface IERC20TestSystem {
  function mint(address to, uint256 amount) external;

  function burn(address from, uint256 amount) external;
}
```

I could register the core contract's function selectors in my module, but if the user overrides one of these base functions, then I will get a ResourceExists revert when installing the module, because it was already registered at root deployment. So I need the IERC20TestSystem interface to inherit from my ERC20System.

**Comment by dk1a** [comment] 2023-05-25 14:18
this seems like a duplicate of https://github.com/latticexyz/mud/issues/631

**Comment by 0xhank** [comment] 2023-05-25 15:36
Oh true

**Closed** 2023-05-25 15:36 UTC
