### ISSUE TITLE
MUD dev-contracts watcher failed to deploy config or contracts changes

### ISSUE THREAD

**Issue by aLIEzsss4** [latticexyz/mud#1010] opened 2023-06-09 10:19 UTC
[MUDError]: Gas estimation error for registerSystem('0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0','73,110,99,114,101,109,101,110,116,83,121,115,116,101,109,0','0x51E8A72176b53f50388418471d771C2805f65e4B','true'): execution reverted

use pnpm mud dev-contracts --tsgenOutput ../client/src/mud -rpc xx

**Comment by alvrs** [comment] 2023-06-09 10:36
can you share your repo to be able to reproduce this issue? to which RRC are you deploying? For development it's recommended to use a local one

**Comment by aLIEzsss4** [comment] 2023-06-09 11:20
I plan to use chainlink, so I can only test on the test network. The version is the latest version. The RPC node is  https://polygon-mumbai.g.alchemy.com/v2/APIKEY. How can I use the online version in the front end? I tried it and there were many errors. Can you give an example version?

**Comment by aLIEzsss4** [comment] 2023-06-09 11:27
> can you share your repo to be able to reproduce this issue? to which RRC are you deploying? For development it's recommended to use a local one

https://github.com/aLIEzsss4/LinkSpark/blob/master/packages/contracts/src/systems/HeroSystem.sol

**Comment by alvrs** [comment] 2023-06-09 12:00
for deploying to a testnet try the `mud deploy` command instead of `mud dev-contracts`. The former waits for transactions to be confirmed before sending the next one while the latter one just hammers the transactions out because the local node is fast enough to handle it. (Also the latter one redeploys every time you change a file, which is probably not what you want when deploying to a remote network)

**Comment by aLIEzsss4** [comment] 2023-06-09 12:18
> for deploying to a testnet try the `mud deploy` command instead of `mud dev-contracts`. The former waits for transactions to be confirmed before sending the next one while the latter one just hammers the transactions out because the local node is fast enough to handle it. (Also the latter one redeploys every time you change a file, which is probably not what you want when deploying to a remote network)

How to use the Mumbai version in the frontend? I have tried it and there are many errors. Can you give an example version?

**Comment by alvrs** [comment] 2023-06-12 14:26
If the deployment succeeded you should be able to specify a `chainId` param to the client url. Could you share a screenshot of the errors you're seeing?

**Comment by holic** [comment] 2023-10-11 10:30
we just rebuild our deploy pipeline in https://github.com/latticexyz/mud/pull/1702, so going to close this as "outdated" for now but feel free to open with reproduction steps if this is still an issue

**Closed by holic** 2023-10-11 10:30 UTC
Labels: help wanted
