### ISSUE TITLE
WSL: New MUD versions don't lint

### ISSUE THREAD

**Issue by 0xhank** [latticexyz/mud#243] opened 2022-11-11 12:02 UTC
I'm getting this error message when I try to commit: 

`.husky/pre-commit: 2: .: Can't open .husky/_/husky.sh`

So i can't make improvement PRs :'(

**Comment by alvrs** [comment] 2022-11-16 11:16
try running `husky install` (should happen automatically in the `prepare` script)

**Comment by alvrs** [comment] 2023-01-04 13:59
@0xhank do you still encounter this issue? I can't reproduce it unfortunately. Closing for now, feel free to reopen if it's still a problem.

**Closed by alvrs** 2023-01-04 13:59 UTC

**Comment by 0xhank** [comment] 2023-01-04 14:04
yeah go ahead and close it, commits seem to be working now
