### ISSUE TITLE
RPC Too Many Requests, interval time during deployment

### ISSUE THREAD

**Issue by aLIEzsss4** [latticexyz/mud#2275] opened 2024-02-16 23:53 UTC
When I deploy MUD on blast, there are limitations due to the shared rpc, which restricts the number of transactions. How should I set the interval time during deployment?

**Comment by holic** [comment] 2024-02-17 14:16
closing as a duplicate of https://github.com/latticexyz/mud/issues/2236

**Closed by holic** 2024-02-17 14:16 UTC
