### ISSUE TITLE
Storage getter not work with hardhat node

### ISSUE THREAD

**Issue by CrazyNorman** [latticexyz/mud#1325] opened 2023-08-18 04:36 UTC
I think this issue is related to the bugs with hardhat node so I raise a issue in the hardhat repo. Just cc to the community here
https://github.com/NomicFoundation/hardhat/issues/4312

**Comment by holic** [comment] 2023-08-18 07:44
This sounds like a hardhat thing rather than a MUD thing?

The way you're calling the world contract directly to get a field makes me think this isn't related to `DELEGATECALL`, I think `DELEGATECALL` happens before it gets to the world when you're using the table libraries.

**Comment by holic** [comment] 2023-08-18 07:44
cc @dk1a in case he has any insight

**Comment by dk1a** [comment] 2023-08-18 08:38
yeah delegatecall is for systems, `getField` is a method of the World contract directly (it's inherited from StoreRead).
Dunno what the problem is, I'm not really familiar with web3 or hardhat node

**Comment by holic** [comment] 2023-09-07 09:34
Going to close this as it sounds like an upstream/tooling issue rather than a MUD issue.

**Closed by holic** 2023-09-07 09:34 UTC
